[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "DecNefSimulator"
description = "DecNefSimulator: A Modular, Interpretable Framework for Decoded Neurofeedback Simulation Using Generative Models"
version = "1.0.0"
authors = [{name="Alexander Olza"}]
license = "AGPL-3.0"
license_files = "LICENSE"
readme = "README.md"
keywords = ["DecNef", "Decoded Neurofeedback", "Cognitive neuroscience"]

[project.urls]
Homepage = "https://github.com/AlexOlza/DecNefSimulator"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
