[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "DecNefSimulator"
version = "1.0.0"
authors = [{name="Alexander Olza"}]
license = {file = "LICENSE"}
readme = "README.md"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]



